project_id = "vnbysqlkaceulzmjhgxc"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.daily-duas]
    verify_jwt = false
  [functions.search-mosques]
    verify_jwt = false
  [functions.fetch-mosque-times]
    verify_jwt = false
  [functions.setup-push]
    verify_jwt = false
  [functions.send-prayer-push]
    verify_jwt = false
